# Generated by Django 5.2.17 on 2026-08-10 10:44

import apps.knowledge.models
import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0003_conversation_customer_optional'),
        ('knowledge', '0001_enable_vector'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('source_key', models.CharField(max_length=255, unique=True, verbose_name='شناسه منبع')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین تغییر')),
            ],
            options={
                'verbose_name': 'سند دانش',
                'verbose_name_plural': 'اسناد دانش',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField(verbose_name='نسخه')),
                ('file', models.FileField(max_length=500, upload_to=apps.knowledge.models.document_upload_path, verbose_name='فایل')),
                ('original_filename', models.CharField(max_length=255, verbose_name='نام فایل اصلی')),
                ('sha256', models.CharField(max_length=64, unique=True, verbose_name='SHA-256')),
                ('file_size', models.PositiveBigIntegerField(default=0, verbose_name='حجم فایل')),
                ('page_count', models.PositiveIntegerField(default=0, verbose_name='تعداد صفحه')),
                ('extracted_character_count', models.PositiveIntegerField(default=0, verbose_name='تعداد نویسه استخراج\u200cشده')),
                ('status', models.CharField(choices=[('pending', 'در انتظار پردازش'), ('ready', 'آماده'), ('needs_ocr', 'نیازمند OCR'), ('failed', 'ناموفق')], db_index=True, default='pending', max_length=16, verbose_name='وضعیت')),
                ('is_active', models.BooleanField(db_index=True, default=False, verbose_name='نسخه فعال')),
                ('error_message', models.TextField(blank=True, verbose_name='خطای پردازش')),
                ('embedding_model', models.CharField(blank=True, max_length=100, verbose_name='مدل بردارسازی')),
                ('embedding_dimensions', models.PositiveIntegerField(default=0, verbose_name='ابعاد بردار')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('indexed_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان ایندکس')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='knowledge.document', verbose_name='سند')),
            ],
            options={
                'verbose_name': 'نسخه سند',
                'verbose_name_plural': 'نسخه\u200cهای اسناد',
                'ordering': ('document', '-version_number'),
            },
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField(verbose_name='شماره صفحه')),
                ('chunk_index', models.PositiveIntegerField(verbose_name='شماره بخش')),
                ('content', models.TextField(verbose_name='متن')),
                ('content_hash', models.CharField(max_length=64, verbose_name='هش متن')),
                ('character_count', models.PositiveIntegerField(verbose_name='تعداد نویسه')),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1024, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='knowledge.documentversion', verbose_name='نسخه سند')),
            ],
            options={
                'verbose_name': 'بخش سند',
                'verbose_name_plural': 'بخش\u200cهای اسناد',
                'ordering': ('version', 'page_number', 'chunk_index'),
            },
        ),
        migrations.CreateModel(
            name='MessageSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity', models.FloatField(verbose_name='امتیاز شباهت')),
                ('rank', models.PositiveSmallIntegerField(verbose_name='رتبه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('chunk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answer_sources', to='knowledge.documentchunk', verbose_name='بخش منبع')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='knowledge_sources', to='chat.message', verbose_name='پیام پاسخ')),
            ],
            options={
                'verbose_name': 'منبع پاسخ',
                'verbose_name_plural': 'منابع پاسخ\u200cها',
                'ordering': ('message', 'rank'),
            },
        ),
        migrations.AddConstraint(
            model_name='documentversion',
            constraint=models.UniqueConstraint(fields=('document', 'version_number'), name='knowledge_document_version_unique'),
        ),
        migrations.AddConstraint(
            model_name='documentversion',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('document',), name='knowledge_one_active_version'),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['version', 'page_number'], name='know_chunk_page_idx'),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='know_chunk_embed_hnsw', opclasses=('vector_cosine_ops',)),
        ),
        migrations.AddConstraint(
            model_name='documentchunk',
            constraint=models.UniqueConstraint(fields=('version', 'page_number', 'chunk_index'), name='knowledge_chunk_position_unique'),
        ),
        migrations.AddIndex(
            model_name='messagesource',
            index=models.Index(fields=['message', 'rank'], name='know_source_rank_idx'),
        ),
        migrations.AddConstraint(
            model_name='messagesource',
            constraint=models.UniqueConstraint(fields=('message', 'chunk'), name='knowledge_message_chunk_unique'),
        ),
    ]
