# Generated by Django 5.2.17 on 2026-08-10 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentversion',
            name='ocr_used',
            field=models.BooleanField(default=False, verbose_name='استخراج با OCR'),
        ),
    ]
