# Generated by Django 5.2.17 on 2026-08-10 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0003_documentversion_ocr_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentversion',
            name='content_verified',
            field=models.BooleanField(db_index=True, default=False, verbose_name='محتوای تأییدشده'),
        ),
    ]
