# Generated by Django 5.2.17 on 2026-08-09 11:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('phone_number', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='شماره تلفن')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('last_seen_at', models.DateTimeField(auto_now=True, verbose_name='آخرین مراجعه')),
            ],
            options={
                'verbose_name': 'مشتری',
                'verbose_name_plural': 'مشتریان',
                'ordering': ('-last_seen_at',),
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'فعال'), ('closed', 'بسته')], db_index=True, default='active', max_length=10, verbose_name='وضعیت')),
                ('language', models.CharField(default='fa', editable=False, max_length=5, verbose_name='زبان')),
                ('kiosk_identifier', models.CharField(blank=True, max_length=100, null=True, verbose_name='شناسه کیوسک')),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='زمان شروع')),
                ('last_activity_at', models.DateTimeField(auto_now=True, verbose_name='آخرین فعالیت')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان پایان')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_conversations', to=settings.AUTH_USER_MODEL, verbose_name='کاربر کیوسک')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversations', to='chat.customer', verbose_name='مشتری')),
            ],
            options={
                'verbose_name': 'گفتگو',
                'verbose_name_plural': 'گفتگوها',
                'ordering': ('-started_at',),
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('customer', 'مشتری'), ('assistant', 'دستیار')], max_length=10, verbose_name='فرستنده')),
                ('content', models.TextField(verbose_name='متن')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='زمان ارسال')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='chat.conversation', verbose_name='گفتگو')),
            ],
            options={
                'verbose_name': 'پیام',
                'verbose_name_plural': 'پیام\u200cها',
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['customer', '-started_at'], name='chat_customer_started_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at'], name='chat_conversation_msg_idx'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(condition=models.Q(('content', ''), _negated=True), name='chat_message_content_not_empty'),
        ),
    ]
